server:
  port: 9002

spring:
  profiles:
    active: dev
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:9296
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2s
      minimumNumberOfCalls: 10
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 5s
      automaticTransitionFromOpenToHalfOpenEnabled: true
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - com.toni.user.exception.BusinessException
  instances:
    userService:
      baseConfig: default
